FROM python:3-alpine
COPY tests/integration/oncat_server.py .
RUN mkdir -p /SNS/CORELLI/IPTS-15526/nexus && \
    touch /SNS/CORELLI/IPTS-15526/nexus/CORELLI_29666.nxs.h5 && \
    mkdir -p /SNS/CORELLI/IPTS-15526/images/det_main && \
    touch /SNS/CORELLI/IPTS-15526/images/det_main/CORELLI_29666_det_main_000001.tiff && \
    mkdir -p /SNS/CORELLI/IPTS-15526/shared/autoreduce && \
    echo '{"output_files":[], "input_files": []}' > /SNS/CORELLI/IPTS-15526/shared/autoreduce/CORELLI_29666.json && \
    \
    mkdir -p /SNS/VENUS/IPTS-99999/nexus && \
    mkdir -p /SNS/VENUS/IPTS-99999/images && \
    mkdir -p /SNS/VENUS/IPTS-99999/shared/autoreduce && \
    touch /SNS/VENUS/IPTS-99999/nexus/VENUS_12345.nxs.h5 && \
    touch /SNS/VENUS/IPTS-99999/nexus/VENUS_12347.nxs.h5 && \
    touch /SNS/VENUS/IPTS-99999/images/20260721_Run_12345_series_0001.fits && \
    touch /SNS/VENUS/IPTS-99999/images/20260721_Run_12345_series_0002.fits && \
    touch /SNS/VENUS/IPTS-99999/images/20260721_Run_12345_series_0003.tiff && \
    touch /SNS/VENUS/IPTS-99999/images/20260721_Run_12347_series_0001.tiff && \
    touch /SNS/VENUS/IPTS-99999/images/20250428_20260721_Run_12345_tpx3_0004.tiff && \
    touch /SNS/VENUS/IPTS-99999/images/20260721_Run_12344_series_0001.tiff && \
    touch /SNS/VENUS/IPTS-99999/images/20260721_Run_123450_series_0001.tiff && \
    \
    mkdir -p /SNS/IMAGING/IPTS-99999/nexus && \
    mkdir -p /SNS/IMAGING/IPTS-99999/images && \
    touch /SNS/IMAGING/IPTS-99999/nexus/IMAGING_12346.nxs.h5 && \
    touch /SNS/IMAGING/IPTS-99999/images/20260721_Run_12346_series_0001.fits && \
    touch /SNS/IMAGING/IPTS-99999/images/20260721_Run_12346_series_0002.fits
CMD ["python", "oncat_server.py"]
