name: Build RPM and Store

permissions:
  contents: write

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build RPM inside Docker
      id: build
      run: |
        docker build --tag postprocess --target=package -f Dockerfile .
        fname=`docker run -v $(pwd):/store postprocess ls /root/rpmbuild/RPMS/noarch`
        docker run -v `pwd`:/store postprocess mv /root/rpmbuild/RPMS/noarch/$fname /store
        one=${fname#*postprocessing-}
        two=${one%.noarch*}
        echo "::set-output name=version::$two"
        echo "::set-output name=fname::$fname"
      continue-on-error: false
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.build.outputs.version }}
        files: |
          ${{ steps.build.outputs.fname }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



